//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CutMicro.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CutMicro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  [Novo Projeto].
        /// </summary>
        public static string @__new_project_ {
            get {
                return ResourceManager.GetString("__new_project_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  (veja lista abaixo)&lt;br&gt;.
        /// </summary>
        public static string @__see_list_below__br_ {
            get {
                return ResourceManager.GetString("__see_list_below__br_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a #1 [234AaZz] 567x890.
        /// </summary>
        public static string _1__234AaZz__567x890 {
            get {
                return ResourceManager.GetString("_1__234AaZz__567x890", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Sobre....
        /// </summary>
        public static string _About___ {
            get {
                return ResourceManager.GetString("_About___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  detalhes com área .
        /// </summary>
        public static string _details_with_area_ {
            get {
                return ResourceManager.GetString("_details_with_area_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Editar.
        /// </summary>
        public static string _Edit {
            get {
                return ResourceManager.GetString("_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Arquivo.
        /// </summary>
        public static string _File {
            get {
                return ResourceManager.GetString("_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Ajuda.
        /// </summary>
        public static string _Help {
            get {
                return ResourceManager.GetString("_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  m².
        /// </summary>
        public static string _m_2 {
            get {
                return ResourceManager.GetString("_m_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  m² (.
        /// </summary>
        public static string _m_2__ {
            get {
                return ResourceManager.GetString("_m_2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  mm.
        /// </summary>
        public static string _mm {
            get {
                return ResourceManager.GetString("_mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Novo.
        /// </summary>
        public static string _New {
            get {
                return ResourceManager.GetString("_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  do .
        /// </summary>
        public static string _of_ {
            get {
                return ResourceManager.GetString("_of_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A&amp;Brir.
        /// </summary>
        public static string _Open {
            get {
                return ResourceManager.GetString("_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Opções.
        /// </summary>
        public static string _Options {
            get {
                return ResourceManager.GetString("_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  pcs)&lt;br&gt;.
        /// </summary>
        public static string _pcs__br_ {
            get {
                return ResourceManager.GetString("_pcs__br_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Imprimir.
        /// </summary>
        public static string _Print {
            get {
                return ResourceManager.GetString("_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  Relatório de impressão.
        /// </summary>
        public static string _printing_report {
            get {
                return ResourceManager.GetString("_printing_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Salvar.
        /// </summary>
        public static string _Save {
            get {
                return ResourceManager.GetString("_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Ferramentas.
        /// </summary>
        public static string _Tools {
            get {
                return ResourceManager.GetString("_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Desfazer.
        /// </summary>
        public static string _Undo {
            get {
                return ResourceManager.GetString("_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a #{0} ({1}) [Largura: {2}{3}{4}{5}.
        /// </summary>
        public static string _Width_ {
            get {
                return ResourceManager.GetString("_Width_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aplicar.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Está certo disso?.
        /// </summary>
        public static string Are_you_sure_ {
            get {
                return ResourceManager.GetString("Are_you_sure_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Área de Cálculo.
        /// </summary>
        public static string Area_calculation {
            get {
                return ResourceManager.GetString("Area_calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Área de uso: .
        /// </summary>
        public static string Area_usage__ {
            get {
                return ResourceManager.GetString("Area_usage__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ÁreaCalc.
        /// </summary>
        public static string AreaCalc {
            get {
                return ResourceManager.GetString("AreaCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Associar com arquivos .cpxml.
        /// </summary>
        public static string Associate {
            get {
                return ResourceManager.GetString("Associate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Isso irá deletar seu design e criará um novo.
        ///Continue?.
        /// </summary>
        public static string Auto_design_msg {
            get {
                return ResourceManager.GetString("Auto_design_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Autosalvar.
        /// </summary>
        public static string Autosave {
            get {
                return ResourceManager.GetString("Autosave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Autosalvar a cada.
        /// </summary>
        public static string Autosave_every {
            get {
                return ResourceManager.GetString("Autosave_every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cor de Fundo.
        /// </summary>
        public static string Background_color {
            get {
                return ResourceManager.GetString("Background_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Comportamento.
        /// </summary>
        public static string Behaviour {
            get {
                return ResourceManager.GetString("Behaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Área calc.
        /// </summary>
        public static string Calc_area {
            get {
                return ResourceManager.GetString("Calc_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pode ser rotacionado.
        /// </summary>
        public static string Can_be_rotated {
            get {
                return ResourceManager.GetString("Can_be_rotated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancelar.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancelar design.
        /// </summary>
        public static string Cancel_design {
            get {
                return ResourceManager.GetString("Cancel_design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não poemos refazer o último movimento.
        /// </summary>
        public static string Cannot_redo_last_move {
            get {
                return ResourceManager.GetString("Cannot_redo_last_move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não pode desfazer último movimento.
        /// </summary>
        public static string Cannot_undo_last_move {
            get {
                return ResourceManager.GetString("Cannot_undo_last_move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Limpar.
        /// </summary>
        public static string Clean {
            get {
                return ResourceManager.GetString("Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clarear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Limpar Detalhes.
        /// </summary>
        public static string Clear_details {
            get {
                return ResourceManager.GetString("Clear_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cl&amp;arear áreas livres.
        /// </summary>
        public static string Clear_free__areas {
            get {
                return ResourceManager.GetString("Clear_free__areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clarear áreas livres.
        /// </summary>
        public static string Clear_free_areas {
            get {
                return ResourceManager.GetString("Clear_free_areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cores &amp; Texto.
        /// </summary>
        public static string Colors___Text {
            get {
                return ResourceManager.GetString("Colors___Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tamanho atual do diretório de altosalve:.
        /// </summary>
        public static string Current_autosave_folder_size_ {
            get {
                return ResourceManager.GetString("Current_autosave_folder_size_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cortar de baixo.
        /// </summary>
        public static string Cut_from_down {
            get {
                return ResourceManager.GetString("Cut_from_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cortar da esquerda.
        /// </summary>
        public static string Cut_from_left {
            get {
                return ResourceManager.GetString("Cut_from_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cortar da direita.
        /// </summary>
        public static string Cut_from_right {
            get {
                return ResourceManager.GetString("Cut_from_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cortar de cima.
        /// </summary>
        public static string Cut_from_up {
            get {
                return ResourceManager.GetString("Cut_from_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a D.
        /// </summary>
        public static string D {
            get {
                return ResourceManager.GetString("D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Padrão.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deletar.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deletar design.
        /// </summary>
        public static string Delete_design {
            get {
                return ResourceManager.GetString("Delete_design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Isso deletará seu design e permitirá a você a editar materiais
        ///Continuar?.
        /// </summary>
        public static string Delete_design_msg {
            get {
                return ResourceManager.GetString("Delete_design_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deletar áreas livres.
        /// </summary>
        public static string Delete_free_areas {
            get {
                return ResourceManager.GetString("Delete_free_areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deletar linhas.
        /// </summary>
        public static string Delete_rows {
            get {
                return ResourceManager.GetString("Delete_rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esse programa é feito para lha ajudar a otimizar o layout de detalhes retangulares.
        ///Para uso em marcenarias, cortes em madeira, montagem de móveis, etc.
        ///Um fork de https://sourceforge.net/projects/ctmc/
        ///
        ///Ícones: Tema ícones H2O(Licença LGPL).
        /// </summary>
        public static string DESCRIPTION_TEXT {
            get {
                return ResourceManager.GetString("DESCRIPTION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Design.
        /// </summary>
        public static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cor dos detalhes.
        /// </summary>
        public static string Detail_color {
            get {
                return ResourceManager.GetString("Detail_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Detalhe do local não iniciado..
        /// </summary>
        public static string Detail_placing_not_started {
            get {
                return ResourceManager.GetString("Detail_placing_not_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Detalhes:.
        /// </summary>
        public static string Details_ {
            get {
                return ResourceManager.GetString("Details_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Detalhes: .
        /// </summary>
        public static string Details__ {
            get {
                return ResourceManager.GetString("Details__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Área de detalhes.
        /// </summary>
        public static string Details_Area {
            get {
                return ResourceManager.GetString("Details_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Larguda limite dos Detalhes: .
        /// </summary>
        public static string Details_edge_length__ {
            get {
                return ResourceManager.GetString("Details_edge_length__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Detalhes nesse painel: &lt;br&gt;.
        /// </summary>
        public static string Details_on_this_panel___br_ {
            get {
                return ResourceManager.GetString("Details_on_this_panel___br_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não rotacionar.
        /// </summary>
        public static string Do_not_rotate {
            get {
                return ResourceManager.GetString("Do_not_rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deseja salvar seu projeto?.
        /// </summary>
        public static string Do_you_want_to_save_your_project_ {
            get {
                return ResourceManager.GetString("Do_you_want_to_save_your_project_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deletar e liberar área.
        /// </summary>
        public static string Drop_and_freearea {
            get {
                return ResourceManager.GetString("Drop_and_freearea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Duplicar.
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &amp;Sair.
        /// </summary>
        public static string E_xit {
            get {
                return ResourceManager.GetString("E_xit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fim do relatório.
        /// </summary>
        public static string End_of_report {
            get {
                return ResourceManager.GetString("End_of_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro: .
        /// </summary>
        public static string Error__ {
            get {
                return ResourceManager.GetString("Error__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sair.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Área Livre. [Largura: .
        /// </summary>
        public static string FAwidth1 {
            get {
                return ResourceManager.GetString("FAwidth1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  Altura: .
        /// </summary>
        public static string FAwidth2 {
            get {
                return ResourceManager.GetString("FAwidth2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ].
        /// </summary>
        public static string FAwidth3 {
            get {
                return ResourceManager.GetString("FAwidth3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Arquivo não encontrado.
        /// </summary>
        public static string File_not_found {
            get {
                return ResourceManager.GetString("File_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Encontrar área máxima.  Alt força a ligar-se ao detalhe mais próximo..
        /// </summary>
        public static string Find_maximum {
            get {
                return ResourceManager.GetString("Find_maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro de carregamento de arquivo:
        ///.
        /// </summary>
        public static string FloadErr {
            get {
                return ResourceManager.GetString("FloadErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fonte.
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Checar à força.
        /// </summary>
        public static string Force_check {
            get {
                return ResourceManager.GetString("Force_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LIVRE.
        /// </summary>
        public static string FREE {
            get {
                return ResourceManager.GetString("FREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cor do traçado da área livre.
        /// </summary>
        public static string Freearea_hatch_color {
            get {
                return ResourceManager.GetString("Freearea_hatch_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro de salvamento do arquivo:.
        /// </summary>
        public static string FSerr {
            get {
                return ResourceManager.GetString("FSerr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cor do traço.
        /// </summary>
        public static string Hatch_color {
            get {
                return ResourceManager.GetString("Hatch_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Altura..
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INDEV..
        /// </summary>
        public static string INDEV_ {
            get {
                return ResourceManager.GetString("INDEV_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor inválido.
        /// </summary>
        public static string Invalid_value {
            get {
                return ResourceManager.GetString("Invalid_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a L .
        /// </summary>
        public static string L_ {
            get {
                return ResourceManager.GetString("L_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cor da linha.
        /// </summary>
        public static string Line_color {
            get {
                return ResourceManager.GetString("Line_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a m².
        /// </summary>
        public static string m_2 {
            get {
                return ResourceManager.GetString("m_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Materiais.
        /// </summary>
        public static string Materials {
            get {
                return ResourceManager.GetString("Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a minutos.
        /// </summary>
        public static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a mm.
        /// </summary>
        public static string mm {
            get {
                return ResourceManager.GetString("mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Novo.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Abrir.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Abrir alto salvamento.
        /// </summary>
        public static string Open_auto_save {
            get {
                return ResourceManager.GetString("Open_auto_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Abrir backup.
        /// </summary>
        public static string Open_backup {
            get {
                return ResourceManager.GetString("Open_backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A&amp;brir relatório no navegador.
        /// </summary>
        public static string Open_report_in__browser {
            get {
                return ResourceManager.GetString("Open_report_in__browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Opções.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Painel #.
        /// </summary>
        public static string Panel__ {
            get {
                return ResourceManager.GetString("Panel__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Painéis.
        /// </summary>
        public static string Panels {
            get {
                return ResourceManager.GetString("Panels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Painéis:.
        /// </summary>
        public static string Panels_ {
            get {
                return ResourceManager.GetString("Panels_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Área dos painéis.
        /// </summary>
        public static string Panels_Area {
            get {
                return ResourceManager.GetString("Panels_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rotacionar.
        /// </summary>
        public static string PHRotate {
            get {
                return ResourceManager.GetString("PHRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MicroCorta.
        /// </summary>
        public static string Program_Productname {
            get {
                return ResourceManager.GetString("Program_Productname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quantidade.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a R .
        /// </summary>
        public static string R_ {
            get {
                return ResourceManager.GetString("R_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Relatório criado em: .
        /// </summary>
        public static string Report_created_at__ {
            get {
                return ResourceManager.GetString("Report_created_at__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rotacionar.
        /// </summary>
        public static string Rotate {
            get {
                return ResourceManager.GetString("Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a S&amp;alvar como.
        /// </summary>
        public static string Save__As {
            get {
                return ResourceManager.GetString("Save__As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar como.
        /// </summary>
        public static string Save_As {
            get {
                return ResourceManager.GetString("Save_As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Largura da serra: .
        /// </summary>
        public static string Saw_width__ {
            get {
                return ResourceManager.GetString("Saw_width__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Largura da serra (mm).
        /// </summary>
        public static string Saw_Width__mm_ {
            get {
                return ResourceManager.GetString("Saw_Width__mm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Largura da Serra (mm).
        /// </summary>
        public static string Saw_Width_mm_ {
            get {
                return ResourceManager.GetString("Saw_Width_mm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Shift.
        /// </summary>
        public static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Shift força a ignorar a linha de corte.
        /// </summary>
        public static string Shift_forces_to_ignore_cutting_line {
            get {
                return ResourceManager.GetString("Shift_forces_to_ignore_cutting_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Shift força a ignorar o fim do painel.
        /// </summary>
        public static string Shift_forces_to_ignore_end_of_panel {
            get {
                return ResourceManager.GetString("Shift_forces_to_ignore_end_of_panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tamanho: .
        /// </summary>
        public static string Size__ {
            get {
                return ResourceManager.GetString("Size__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Levar para o próximo detalhe. Alt força para encontrar a área máxima.
        /// </summary>
        public static string Snap {
            get {
                return ResourceManager.GetString("Snap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ordenar detalhes.
        /// </summary>
        public static string Sort_details {
            get {
                return ResourceManager.GetString("Sort_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ordenar detalhes pela altura.
        /// </summary>
        public static string Sort_details_height {
            get {
                return ResourceManager.GetString("Sort_details_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ordenar detalhes pelo id.
        /// </summary>
        public static string Sort_details_id {
            get {
                return ResourceManager.GetString("Sort_details_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ordenar detalhes pela largura.
        /// </summary>
        public static string Sort_details_width {
            get {
                return ResourceManager.GetString("Sort_details_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ordenar oficina..
        /// </summary>
        public static string Sort_workshop {
            get {
                return ResourceManager.GetString("Sort_workshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Começar Cálculo.
        /// </summary>
        public static string Start_calculating {
            get {
                return ResourceManager.GetString("Start_calculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Começar design.
        /// </summary>
        public static string Start_design {
            get {
                return ResourceManager.GetString("Start_design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status: Falha. Confira os dados digitados.
        /// </summary>
        public static string Status_Fail {
            get {
                return ResourceManager.GetString("Status_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status: OK!.
        /// </summary>
        public static string Status_OK {
            get {
                return ResourceManager.GetString("Status_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Texto.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cor do texto.
        /// </summary>
        public static string Text_color {
            get {
                return ResourceManager.GetString("Text_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aparar: .
        /// </summary>
        public static string Trim__ {
            get {
                return ResourceManager.GetString("Trim__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aparar abaixo.
        /// </summary>
        public static string Trim_Down {
            get {
                return ResourceManager.GetString("Trim_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aparar esquerda.
        /// </summary>
        public static string Trim_left {
            get {
                return ResourceManager.GetString("Trim_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aparar direita.
        /// </summary>
        public static string Trim_right {
            get {
                return ResourceManager.GetString("Trim_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aparar acima.
        /// </summary>
        public static string Trim_up {
            get {
                return ResourceManager.GetString("Trim_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a U .
        /// </summary>
        public static string U_ {
            get {
                return ResourceManager.GetString("U_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desfazer último movimento.
        /// </summary>
        public static string Undo_last_move {
            get {
                return ResourceManager.GetString("Undo_last_move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Detalhes não colocados:.
        /// </summary>
        public static string Unplaced_details__ {
            get {
                return ResourceManager.GetString("Unplaced_details__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Area usável dos painéis.
        /// </summary>
        public static string Usable_Panels_Area {
            get {
                return ResourceManager.GetString("Usable_Panels_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Largura.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro de largura ou altura.
        /// </summary>
        public static string Width_or_height_error {
            get {
                return ResourceManager.GetString("Width_or_height_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você tem o total .
        /// </summary>
        public static string You_have_total_ {
            get {
                return ResourceManager.GetString("You_have_total_", resourceCulture);
            }
        }
    }
}
